// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqnLSwS7LKKMixFX4lhSxMqK0ja9bMjpE',
    appId: '1:321522792057:web:575c5dfd187b462034c6a8',
    messagingSenderId: '321522792057',
    projectId: 'chat-application-8d1df',
    authDomain: 'chat-application-8d1df.firebaseapp.com',
    storageBucket: 'chat-application-8d1df.appspot.com',
    measurementId: 'G-XHLTG5KXP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfB86YJDLX2C6oLY4sRH2G-Kwruuv3C_E',
    appId: '1:321522792057:android:4c0debe8b2e952b434c6a8',
    messagingSenderId: '321522792057',
    projectId: 'chat-application-8d1df',
    storageBucket: 'chat-application-8d1df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcip_QdAtOG7ougfHq-69bAsBVKP5Gfg',
    appId: '1:321522792057:ios:d2af392791a84add34c6a8',
    messagingSenderId: '321522792057',
    projectId: 'chat-application-8d1df',
    storageBucket: 'chat-application-8d1df.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
